# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional

from pydantic import Field as FieldInfo

from .._models import BaseModel

__all__ = ["LinkListResponse", "Meta", "Object", "ObjectTag"]


class Meta(BaseModel):
    current_page: Optional[int] = None
    """The current page number."""

    from_: Optional[int] = FieldInfo(alias="from", default=None)
    """The first record of the current page"""

    last_page: Optional[int] = None
    """The last page number."""

    next_page: Optional[int] = None
    """The next page number, can be null if on last page."""

    path: Optional[str] = None
    """The base API endpoint for the current request."""

    per_page: Optional[int] = None
    """The items per page"""

    previous_page: Optional[int] = None
    """The previous page number, can be null if on first page."""

    to: Optional[int] = None
    """The last record of the current page"""

    total: Optional[int] = None
    """The total number of records in all pages. Unrelated to count or sum queries."""


class ObjectTag(BaseModel):
    name: Optional[str] = None
    """The tag name"""

    shared: Optional[bool] = None
    """Indicates if this tag is shared with other users"""


class Object(BaseModel):
    id: Optional[int] = None
    """This is the link's id, and corresponds to the {link_id} in other API endpoints"""

    alias: Optional[str] = None
    """The URI portion of the short link.

    Will be autogenerated if not defined by client
    """

    archive_on: Optional[int] = None

    click_count: Optional[int] = None

    created: Optional[int] = None

    delete_on: Optional[int] = None

    domain_id: Optional[int] = None

    modified: Optional[int] = None

    notes: Optional[str] = None

    notify_on_click: Optional[str] = None

    redirect_type: Optional[int] = None

    redirect_url: Optional[str] = None

    short_link: Optional[str] = None

    status: Optional[str] = None

    tags: Optional[List[ObjectTag]] = None
    """Array of objects defining tags to be attached to the link"""

    template_id: Optional[int] = None

    url: Optional[str] = None

    user_id: Optional[int] = None


class LinkListResponse(BaseModel):
    click_count: Optional[int] = None
    """Total number of clicks for all links found not just the ones returned."""

    count: Optional[int] = None
    """Number of links returned in the `objects` array"""

    meta: Optional[Meta] = None
    """A set of meta data unrelated to the query but useful in various API scenarios."""

    objects: Optional[List[Object]] = None

    total: Optional[int] = None
    """Total number of links found by query"""
